name: Deploy
run-name: DEPLOY 🚀
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no nor@200.17.32.223
          mkdir teste
    
      
      
