name: Deploy
run-name: DEPLOY 🚀
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      
      - name: Compress the repository
        run: |
          git archive --format=tar.gz --output=projeto.tar.gz HEAD
      
      - name: Transfer file to server
        run: |
          scp -o StrictHostKeyChecking=no projeto.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/nor/workspace/projetonode
      
      - name: Execute SSH commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          cd /home/nor/workspace/projetonode
          cd projetonode/
          tar -xf projeto.tar.gz
          rm -rf projeto.tar.gz
          touch teste.txt
          EOF
