name: Deploy
run-name: DEPLOY 🚀
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Prepare SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_SSH_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      
      - name: Compress the repository
        run: |
          git archive --format=tar.gz --output=projeto.tar.gz HEAD
      
      - name: Transfer file to server
        run: |
          scp -i ~/.ssh/id_rsa -P ${{ secrets.SERVER_SSH_PORT }} projeto.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/nor/workspace/projetonode/projeto.tar.gz
          #scp -o StrictHostKeyChecking=no projeto.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/nor/
      
      - name: Execute SSH commands on remote server
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SERVER_SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          #ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          cd /home/nor/workspace/projetonode
          tar -xf projeto.tar.gz
          rm -rf projeto.tar.gz
          docker-compose down
          docker-compose up -d --build
         
          EOF
